### ISSUE TITLE
Dictionary Builder doesn't import if there is nothing to map

### ISSUE THREAD

**Issue by clbx** [etown-blue-team/Otis#18]
If a dataset has nothing to map (is all numbers)

Something like:

```
0,0,0,0
0,1,1,1
1,0,1,1
0,1,0,1
1,0,1,1
1,1,1,0
0,0,0,0
```
Doesn't get processed and when attempting to view, Otis says that the dataframe is empty

Changing the imported data to something like 
```
0,0,a,0
0,1,b,1
1,0,b,1
0,1,a,1
1,0,b,1
1,1,b,0
0,0,a,0
```
Allows it to be imported

Something in there is skipping importing if there is nothing to map

**Comment by Lousheng** [comment]
Should be updated and fixed in the dict_builder branch
